import Foundation
import SwiftData
import Testing
@testable import timetracker

@Suite(.serialized)
struct DemoDataLifecycleTests {
    @Test @MainActor
    func demoDataContainsMultiDayAnalyticsAndActiveTimers() throws {
        prepareAutomaticDemoSeeding()
        defer { resetDemoSeedingDefaults() }
        let context = try makeTestContext()
        try SeedData.replaceWithDemoData(context: context)

        let taskRepository = SwiftDataTaskRepository(context: context, deviceID: "test")
        let timeRepository = SwiftDataTimeTrackingRepository(context: context, deviceID: "test")
        let pomodoroRepository = SwiftDataPomodoroRepository(context: context, timeRepository: timeRepository, deviceID: "test")

        #expect(try taskRepository.allNodes().count >= 10)
        #expect(try timeRepository.allSegments().count >= 40)
        #expect(try timeRepository.activeSegments().count == 2)
        #expect(try pomodoroRepository.runs().contains { $0.state == .completed })

        let store = makeTestStore()
        store.configureIfNeeded(context: context)
        let overview = store.analyticsOverview(for: .week)
        #expect(overview.grossSeconds > overview.wallSeconds)
        #expect(store.taskBreakdown(range: .week).isEmpty == false)
    }

    @Test @MainActor
    func replacingDemoDataClearsExistingLedgerBeforeSeeding() throws {
        prepareAutomaticDemoSeeding()
        defer { resetDemoSeedingDefaults() }
        let context = try makeTestContext()
        let taskRepository = SwiftDataTaskRepository(context: context, deviceID: "test")
        let timeRepository = SwiftDataTimeTrackingRepository(context: context, deviceID: "test")
        let oldTask = try taskRepository.createTask(title: "Temporary Task", parentID: nil, colorHex: nil, iconName: nil)
        _ = try timeRepository.addManualSegment(
            taskID: oldTask.id,
            startedAt: Date().addingTimeInterval(-600),
            endedAt: Date(),
            note: nil
        )

        try SeedData.replaceWithDemoData(context: context)

        #expect(try taskRepository.allNodes().contains { $0.title == "Temporary Task" } == false)
        #expect(try timeRepository.allSegments().contains { $0.taskID == oldTask.id } == false)
        #expect(try timeRepository.activeSegments().count == 2)
        #expect(SeedData.isAutomaticDemoSeedingDisabled == false)
    }

    @Test @MainActor
    func clearingDemoDataKeepsUserCreatedRecords() throws {
        prepareAutomaticDemoSeeding()
        defer { resetDemoSeedingDefaults() }
        let context = try makeTestContext()
        try SeedData.replaceWithDemoData(context: context)

        let taskRepository = SwiftDataTaskRepository(context: context, deviceID: "test")
        let timeRepository = SwiftDataTimeTrackingRepository(context: context, deviceID: "test")
        let userTask = try taskRepository.createTask(title: "Real Work", parentID: nil, colorHex: nil, iconName: nil)
        _ = try timeRepository.addManualSegment(
            taskID: userTask.id,
            startedAt: Date().addingTimeInterval(-900),
            endedAt: Date(),
            note: nil
        )

        try SeedData.clearDemoData(context: context)

        #expect(try taskRepository.allNodes().map(\.title) == ["Real Work"])
        #expect(try timeRepository.allSegments().count == 1)
        #expect(try timeRepository.activeSegments().isEmpty)
        #expect(SeedData.isAutomaticDemoSeedingDisabled)
    }

    @Test @MainActor
    func clearingDemoDataAlsoRemovesGeneratedRecurrenceChildren() throws {
        prepareAutomaticDemoSeeding()
        defer { resetDemoSeedingDefaults() }
        let context = try makeTestContext()
        let template = TaskNode(
            title: "Demo repeating template",
            parentID: nil,
            deviceID: "demo"
        )
        let rule = TaskRecurrenceRule(
            templateTaskID: template.id,
            startDayKey: "2026-07-20",
            timeZoneIdentifier: "Asia/Singapore",
            deviceID: "demo"
        )
        let occurrence = TaskRecurrenceOccurrence(
            ruleID: rule.id,
            templateTaskID: template.id,
            occurrenceDayKey: "2026-07-20",
            timeZoneIdentifier: rule.timeZoneIdentifier,
            deviceID: "local-device"
        )
        let generatedTask = TaskNode(
            title: "Generated by demo rule",
            parentID: template.id,
            deviceID: "local-device"
        )
        generatedTask.id = occurrence.generatedTaskID
        let goal = TaskQuantityGoal(
            taskID: generatedTask.id,
            targetAmount: 50,
            unitLabel: "push-ups",
            deviceID: "local-device"
        )
        let entry = TaskQuantityEntry(
            id: UUID(),
            taskID: generatedTask.id,
            amount: 10,
            deviceID: "local-device"
        )
        context.insert(template)
        context.insert(rule)
        context.insert(occurrence)
        context.insert(generatedTask)
        context.insert(goal)
        context.insert(entry)
        try context.save()

        try SeedData.clearDemoData(context: context)

        #expect(template.deletedAt != nil)
        #expect(generatedTask.deletedAt != nil)
        #expect(rule.deletedAt != nil)
        #expect(occurrence.deletedAt != nil)
        #expect(goal.deletedAt != nil)
        #expect(entry.deletedAt != nil)
    }

    @Test @MainActor
    func clearingDemoDataPreventsAutomaticReseedingOnNextLaunch() throws {
        prepareAutomaticDemoSeeding()
        defer { resetDemoSeedingDefaults() }
        let context = try makeTestContext()

        try SeedData.ensureSeeded(context: context)
        #expect(try context.fetch(FetchDescriptor<TaskNode>()).isEmpty == false)

        try SeedData.clearDemoData(context: context)
        #expect(try context.fetch(FetchDescriptor<TaskNode>()).visibleDeduplicatedByID().isEmpty)
        #expect(SeedData.isAutomaticDemoSeedingDisabled)

        try SeedData.ensureSeeded(context: context)
        #expect(try context.fetch(FetchDescriptor<TaskNode>()).visibleDeduplicatedByID().isEmpty)
    }

    @Test @MainActor
    func rebuildingDemoDataReenablesAutomaticDemoSeeding() throws {
        prepareAutomaticDemoSeeding(disabled: true)
        defer { resetDemoSeedingDefaults() }
        let context = try makeTestContext()

        try SeedData.replaceWithDemoData(context: context)

        #expect(SeedData.isAutomaticDemoSeedingDisabled == false)
        #expect(try context.fetch(FetchDescriptor<TaskNode>()).isEmpty == false)
    }

    @Test @MainActor
    func automaticDemoDataCanBeDisabledByBuildConfiguration() throws {
        prepareAutomaticDemoSeeding(demoMode: .off)
        defer { resetDemoSeedingDefaults() }
        let context = try makeTestContext()

        try SeedData.ensureSeeded(context: context)

        #expect(try context.fetch(FetchDescriptor<TaskNode>()).isEmpty)
    }

    @Test @MainActor
    func demoDataCannotBeRebuiltWhileTheProductionStoreIsOpen() throws {
        // Mode `off` is what ships, and it means the app opened the real
        // CloudKit-backed store. Rebuilding demo data there would tombstone the
        // user's rows and sync both the deletions and the demo rows to iCloud.
        prepareAutomaticDemoSeeding(demoMode: .off)
        defer { resetDemoSeedingDefaults() }

        #expect(AppDemoDataConfiguration.usesLocalDemoStore == false)
        #expect(AppDemoDataConfiguration.allowsDemoDataMutation == false)

        let context = try makeTestContext()
        let taskRepository = SwiftDataTaskRepository(context: context, deviceID: "test")
        let userTask = try taskRepository.createTask(
            title: "Real Work",
            parentID: nil,
            colorHex: nil,
            iconName: nil
        )

        #expect(throws: SeedData.SeedDataError.self) {
            try SeedData.replaceWithDemoData(context: context)
        }

        // The user's row survives untouched — no tombstone, no demo rows.
        #expect(try taskRepository.allNodes().map(\.title) == ["Real Work"])
        #expect(userTask.deletedAt == nil)
    }

    @Test @MainActor
    func demoDataRebuildIsAllowedOnceTheIsolatedDemoStoreIsSelected() throws {
        prepareAutomaticDemoSeeding(demoMode: .seedIfEmpty)
        defer { resetDemoSeedingDefaults() }

        #expect(AppDemoDataConfiguration.usesLocalDemoStore)
        #expect(AppDemoDataConfiguration.allowsDemoDataMutation)

        let context = try makeTestContext()
        try SeedData.replaceWithDemoData(context: context)

        #expect(try context.fetch(FetchDescriptor<TaskNode>()).isEmpty == false)
    }

    @Test
    func theDemoStoreIsAFileSeparateFromTheProductionStore() {
        let demoURL = AppDemoDataConfiguration.persistentStoreURL
        let productionURL = AppCloudSync.persistentStoreURL

        #expect(demoURL != productionURL)
        #expect(demoURL.lastPathComponent == "TimeTracker-Demo.store")
        #expect(demoURL.deletingLastPathComponent() == productionURL.deletingLastPathComponent())
    }

    @Test @MainActor
    func clearingDemoDataAlsoRemovesSmokeTestAndUITestResidue() throws {
        defer { resetDemoSeedingDefaults() }
        let context = try makeTestContext()

        // A cloud smoke-test probe used to survive "clear demo data", because
        // the cleanup only recognised the `demo` device ID.
        let smokeTask = TaskNode(
            title: "Cloud Smoke a1b2c3d4",
            parentID: nil,
            deviceID: SyntheticDataOrigin.cloudSmokeTest
        )
        let fixtureItem = InboxItem(
            title: "UI fixture item",
            sortOrder: 10,
            deviceID: SyntheticDataOrigin.uiTest
        )
        let userTask = TaskNode(title: "Real Work", parentID: nil, deviceID: "local-device")
        let userItem = InboxItem(title: "first", sortOrder: 20, deviceID: "local-device")
        [smokeTask, userTask].forEach(context.insert)
        [fixtureItem, userItem].forEach(context.insert)
        try context.save()

        try SeedData.clearDemoData(context: context)

        #expect(smokeTask.deletedAt != nil)
        #expect(fixtureItem.deletedAt != nil)
        // Rows the user authored are never touched, whatever they are titled.
        #expect(userTask.deletedAt == nil)
        #expect(userItem.deletedAt == nil)
    }

    @Test
    func syntheticOriginsCoverEveryProducerOfNonUserRows() {
        #expect(SyntheticDataOrigin.marks(SyntheticDataOrigin.demo))
        #expect(SyntheticDataOrigin.marks(SyntheticDataOrigin.cloudSmokeTest))
        #expect(SyntheticDataOrigin.marks(SyntheticDataOrigin.uiTest))
        #expect(SyntheticDataOrigin.marks("local-device") == false)
        #expect(SyntheticDataOrigin.marks(DeviceIdentity.current) == false)
    }

    @Test
    func theShippedBuildConfigurationNeverEnablesAutomaticSeeding() throws {
        // A configuration gate, not a logic scan: the pbxproj is the only place
        // the shipped Info.plist value is declared.
        let projectSource = try sourceText("timetracker.xcodeproj/project.pbxproj")

        #expect(projectSource.contains("TIMETRACKER_AUTOMATIC_DEMO_DATA_MODE = seedIfEmpty;") == false)
        #expect(projectSource.contains("TIMETRACKER_AUTOMATIC_DEMO_DATA_MODE = replaceOnLaunch;") == false)
        #expect(projectSource.contains("TIMETRACKER_AUTOMATIC_DEMO_DATA_MODE = off;"))
    }

    @Test
    func commandLineDemoModeDoesNotDependOnUserDefaultsArgumentDomain() {
        let key = AppDemoDataConfiguration.overrideKey

        #expect(
            AppDemoDataConfiguration.commandLineMode(
                arguments: ["timetracker", "-\(key)", "replaceOnLaunch"]
            ) == .replaceOnLaunch
        )
        #expect(
            AppDemoDataConfiguration.commandLineMode(
                arguments: ["timetracker", "-\(key)=seedIfEmpty"]
            ) == .seedIfEmpty
        )
        #expect(
            AppDemoDataConfiguration.commandLineMode(
                arguments: ["timetracker", "-\(key)", "unsupported"]
            ) == nil
        )
    }

    @Test @MainActor
    func screenshotDemoModeRebuildsDataOnLaunch() throws {
        prepareAutomaticDemoSeeding(demoMode: .replaceOnLaunch, disabled: true)
        defer { resetDemoSeedingDefaults() }
        let context = try makeTestContext()
        let taskRepository = SwiftDataTaskRepository(context: context, deviceID: "test")
        _ = try taskRepository.createTask(title: "Should Be Replaced", parentID: nil, colorHex: nil, iconName: nil)

        try SeedData.ensureSeeded(context: context)

        let rows = try context.fetch(FetchDescriptor<TaskNode>())
        let titles = rows.visibleDeduplicatedByID().map(\.title)
        #expect(titles.contains("Should Be Replaced") == false)
        #expect(titles.contains("Time Tracker App"))
        #expect(rows.contains { $0.title == "Should Be Replaced" && $0.deletedAt != nil })
        #expect(SeedData.isAutomaticDemoSeedingDisabled == false)
    }

    @Test @MainActor
    func automaticDemoDataDoesNotSeedIntoCloudBackedStorage() throws {
        prepareAutomaticDemoSeeding(mode: AppCloudSync.modeICloud)
        defer { resetDemoSeedingDefaults() }
        let context = try makeTestContext()

        try SeedData.ensureSeeded(context: context)

        #expect(try context.fetch(FetchDescriptor<TaskNode>()).isEmpty)
    }

    @Test @MainActor
    func automaticDemoDataDoesNotSeedIntoFallbackStorage() throws {
        defer { resetDemoSeedingDefaults() }
        for mode in [AppCloudSync.modeLocalFallback, AppCloudSync.modeInMemoryFallback] {
            prepareAutomaticDemoSeeding(mode: mode, lastError: "Persistent store unavailable")
            let context = try makeTestContext()

            try SeedData.ensureSeeded(context: context)

            #expect(try context.fetch(FetchDescriptor<TaskNode>()).isEmpty)
        }
    }

    @MainActor
    private func prepareAutomaticDemoSeeding(
        mode: String = "Local",
        demoMode: AutomaticDemoDataMode = .seedIfEmpty,
        disabled: Bool = false,
        lastError: String? = nil
    ) {
        AppDefaults.shared.set(demoMode.rawValue, forKey: AppDemoDataConfiguration.overrideKey)
        AppDefaults.shared.set(disabled, forKey: SeedData.automaticDemoSeedingDisabledKey)
        AppDefaults.shared.set(mode, forKey: AppCloudSync.modeKey)
        if let lastError {
            AppDefaults.shared.set(lastError, forKey: AppCloudSync.errorKey)
        } else {
            AppDefaults.shared.removeObject(forKey: AppCloudSync.errorKey)
        }
    }

    @MainActor
    private func resetDemoSeedingDefaults() {
        AppDefaults.shared.removeObject(forKey: AppDemoDataConfiguration.overrideKey)
        AppDefaults.shared.removeObject(forKey: SeedData.automaticDemoSeedingDisabledKey)
        AppDefaults.shared.removeObject(forKey: AppCloudSync.modeKey)
        AppDefaults.shared.removeObject(forKey: AppCloudSync.errorKey)
        AppDefaults.shared.removeObject(forKey: AppCloudSync.accountStatusKey)
    }
}
