#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROFILE="${TIMETRACKER_STRESS_PROFILE:-${1:-large}}"
DESTINATION="${TIMETRACKER_STRESS_DESTINATION:-platform=macOS}"
SCHEME="${TIMETRACKER_STRESS_SCHEME:-timetracker}"
RESULT_ROOT="${TIMETRACKER_STRESS_RESULT_ROOT:-$ROOT_DIR/build/StressDataResults}"
RESULT_BUNDLE="$RESULT_ROOT/stress-${PROFILE}-$(date +%Y%m%d-%H%M%S).xcresult"

mkdir -p "$RESULT_ROOT"

echo "Running stress data UI test"
echo "  profile:     $PROFILE"
echo "  destination: $DESTINATION"
echo "  result:      $RESULT_BUNDLE"

cd "$ROOT_DIR"
TIMETRACKER_STRESS_PROFILE="$PROFILE" \
TIMETRACKER_STRESS_ROOTS="${TIMETRACKER_STRESS_ROOTS:-}" \
TIMETRACKER_STRESS_DEPTH="${TIMETRACKER_STRESS_DEPTH:-}" \
TIMETRACKER_STRESS_CHILDREN="${TIMETRACKER_STRESS_CHILDREN:-}" \
TIMETRACKER_STRESS_CHECKLIST_ITEMS="${TIMETRACKER_STRESS_CHECKLIST_ITEMS:-}" \
TIMETRACKER_STRESS_SEGMENTS="${TIMETRACKER_STRESS_SEGMENTS:-}" \
TIMETRACKER_STRESS_CATEGORIES="${TIMETRACKER_STRESS_CATEGORIES:-}" \
TIMETRACKER_STRESS_INBOX_ITEMS="${TIMETRACKER_STRESS_INBOX_ITEMS:-}" \
TIMETRACKER_STRESS_COUNTDOWNS="${TIMETRACKER_STRESS_COUNTDOWNS:-}" \
xcodebuild test \
    -scheme "$SCHEME" \
    -destination "$DESTINATION" \
    -only-testing:timetrackerUITests/timetrackerStressDataUITests/testStressDataProfileLaunchesCoreSurfaces \
    -resultBundlePath "$RESULT_BUNDLE"
